* org-mode configuration                                                  :noexport:
#+STARTUP: overview customtime noalign logdone hidestars
#+SEQ_TODO: TODO HALF ASSIGN | DONE BYPASS DELEGATE CANCELED DEFERRED
#+DRAWERS: HIDDEN CODE CONF EMAIL WEBPAGE SNIP
#+PRIORITIES: A D C
#+ARCHIVE: %s_done::** Finished Tasks
#+AUTHOR: dennyzhang.com (denny@dennyzhang.com)
#+OPTIONS: creator:nil
#+OPTIONS: toc:3 \n:t ^:nil creator:nil d:nil
* Update Address
** HALF Register your new address in the new state with the United States Postal Service (USPS).
https://www.mymovingreviews.com/move/change-address-when-moving

http://usps.com/move

It will charge you for $1
https://www.mymovingreviews.com/move/move-from-one-state-to-another
#+BEGIN_EXAMPLE
Change of address. You’re moving from one state to another state, and that automatically means that your postal address will change too. So, you’re going to have to register your new address in the new state with the United States Postal Service (USPS).
#+END_EXAMPLE
** HALF notify U.S. Citizenship and Immigration Services (US CIS) of any change of address (Form AR-11) within 10 days of a move
https://www.uscis.gov/addresschange

Most non-U.S. citizens must report a change of address within 10 days of moving within the United States or its territories.

The primary purpose for collecting your case receipt number is to provide you with a status update and estimated processing times for a pending immigration benefit application or petition.
** Update billing address of credit cards
* Update Vehicle
** Change auto insurance
** car smog certificate
https://www.dmv.org/ca-california/smog-check.php
#+BEGIN_EXAMPLE
In California, vehicles must undergo a biennial smog inspection in order to renew your registration. New residents to California will be required to have an initial inspection to register, even if you have a current certificate from your previous state. Testing can be completed at DMV-approved locations throughout your county. Safety inspections are not generally required for registration or renewal.

In California, most vehicles are required to be smog checked every 2 years. Keep reading below for information about smog inspections in California, including forms and fees you'll need to provide.
#+END_EXAMPLE

https://smogcheck.ca.gov/pubwebquery/Station/StationList.aspx?DisplayResults=Y&ZIP=94043
#+BEGIN_EXAMPLE
RC239871	STAR
Test and Repair	Y	Y	Mountain View Radiator
1905 Old Midelfield Way
Mountain View, CA 94043	650-968-9146	Santa Clara	San Jose	Y	Y
RC217167	Test and Repair	N	N	Helmings Auto Repair
2520 Wyandotte St #G
Mountain View, CA 94043	650-988-0460	Santa Clara	San Jose	Y	Y
TC232245	STAR
Test Only	Y	N	Jorge'S Smog
740 Sierra Vista Ave L
Mountain View, CA 94043	650-969-3211	Santa Clara	San Jose	Y	Y
RC275242	Test and Repair	N	N	Peninsula Auto Repair
790 Shoreline Blvd
Mountain View, CA 94043	650-960-1300	Santa Clara	San Jose	Y	Y
RC250602	STAR
Test and Repair	Y	Y	Driven Auto Care Inc
826 Rengstorff Ave
Mountain View, CA 94043	650-967-3569	Santa Clara	San Jose	Y       Y
#+END_EXAMPLE
** Find Local DMV Office
*** DMV Office in Santa Clara
https://www.dmv.ca.gov/portal/dmv/detail/fo/offices/fieldoffice?number=632
3665 Flora Vista Ave
Santa Clara, CA 95051

(800)777-0133

#+BEGIN_EXAMPLE
Mon
8:00 AM
5:00 PM
Tue
8:00 AM
5:00 PM
Wed
9:00 AM
5:00 PM
Thur
8:00 AM
5:00 PM
Fri
8:00 AM
5:00 PM
Sat
Closed
Sun
Closed
This office is open on Saturday, June 16 and 23, from 8 a.m. to 1 p.m.
#+END_EXAMPLE
** [#A] Car registration
https://www.dmv.org/ca-california/car-registration.php
#+BEGIN_EXAMPLE
How to Register Your Vehicle in California
Visit a local CA DMV office.
Present proof of ownership and a smog certificate.
Provide proof of your ID and car insurance.
Complete a Application for Title or Registration (Form REG 343).
Pay the $58 registration fee, $25 CHP fee, Transportation Improvement fee, title fees, and taxes.
For more details, please see below.
#+END_EXAMPLE

https://www.mymovingreviews.com/move/move-from-one-state-to-another
https://yogov.org/dmv/california/need-change-address-california-drivers-license/
#+BEGIN_EXAMPLE
Car registration. If you’re wondering whether you are required to register your car after moving to a new state, the short answer is YES. Regrettably, you won’t be able to complete this task online, so you’ll really need to find time in your busy schedule and do it in person at a local DMV office.

It’s important to note that different U.S. states have different deadlines for vehicle registration – some will give you one month to do it, while others require you to do it within 10 days (Florida). Contact the nearest DMV office to learn what documents you will need for the registration process – note that a car insurance policy, purchased from the destination state, is a must.
#+END_EXAMPLE
*** Update vehicle plate
** [#A] Get a new driver’s license
https://www.dmv.org/ca-california/apply-license.php
#+BEGIN_EXAMPLE
Applying for a California Driver's License
How to get a driver's license with the California Department of Motor Vehicles (DMV):

Visit your local CA DMV office.
Complete a Driver License or Identification Card Application (Form DL 44).
Provide proof of your identity, Social Security Number, and residency.
Pay the $35 driver's license fee.
Pass the written test.
Pass the road test.
For more details on the California licensing requirements, please see below.
#+END_EXAMPLE

Note, however, that the California DMV will most likely waive your driving exam if you already hold a license* UNLESS your license is from another country (see our section on non-citizens below).

https://www.moving.com/tips/your-checklist-for-moving-to-another-state/
#+BEGIN_EXAMPLE
Want to drive in your new state? You’ll need a new driver’s license from your state’s DMV. Be sure to check your state’s requirements, as many states require new residents to obtain their driver’s license within a specific time window after moving. Keep in mind that while requirements for transferring a driver’s license vary from state to state, you’ll most likely need a driver’s license, proof of residency, proof of your social security number and an additional form of identification.
#+END_EXAMPLE
*** Samples of Driver License Knowledge Tests
https://www.dmv.ca.gov/portal/dmv/detail/pubs/interactive/tdrive/exam
*** DONE California Driver Handbook
   CLOSED: [2018-06-04 Mon 16:06]
https://www.dmv.ca.gov/portal/dmv/detail/pubs/interactive/tdrive/exam
** Get a new vehicle
** Change your address on the State of California DMV website
https://yogov.org/dmv/california/need-change-address-california-drivers-license/
https://www.dmv.ca.gov/portal/dmv
* Update address in your employer's system
* Change Health care providers
https://www.mymovingreviews.com/move/move-from-one-state-to-another
#+BEGIN_EXAMPLE
Health care providers. Moving to another state also means that you’re expected to find new health care providers for you and your family members, including your pet. Remember that your health, and the health of the people around you, is a top priority no matter what happens.

Regardless of whether you’ll be looking for primary care doctors, specialized doctors or licensed vets, you will need the necessary documentation for the registration process. Usually, the required documents are medical records and vaccination papers which you should have requested from your old physician and veterinarian prior to the actual move.
#+END_EXAMPLE
* useful link
https://www.quora.com/Whats-involved-in-moving-from-one-state-to-another-in-the-US

What's involved in moving from one state to another in the US? - Quora

https://www.dmv.org/moving-relocation-checklist.php?from=77007&to=94043&date=2018-06-04&ownership=rent
Moving Checklist | DMV.ORG
